import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import PostList from './PostList';
import Welcome from './Welcome';
import LoginForm from './LoginForm';
import ReactStackForm from './chapter02/ReactStackForm';
import SimpleForm from './chapter02/SimpleForm';
import Hello from './chapter04/Hello';
import UserListContainer from './chapter04/UserListContainer';
import Container from './chapter04/Container';

ReactDOM.render(<App />, document.getElementById('root'));
// ReactDOM.render(<PostList />,document.getElementById("root"));
// ReactDOM.render(<Welcome />,document.getElementById("root"));
// ReactDOM.render(<LoginForm />,document.getElementById("root"));
// ReactDOM.render(<ReactStackForm />,document.getElementById("root"));
// ReactDOM.render(<SimpleForm />,document.getElementById("root"));
// ReactDOM.render(<Hello />,document.getElementById("root"));
// ReactDOM.render(<UserListContainer />,document.getElementById("root"));
ReactDOM.render(<Container />,document.getElementById("root"));
registerServiceWorker();
